### PR TITLE
Add GHA, fix compilation issues

### PR DESCRIPTION
**Pull request by csoneson**

### CODE REVIEW

**Review by mbstadler — APPROVED** [review]
This all looks great to me. I currently see two open issues that you have also already mentioned:

- We should probably add the `SystemRequirements: GNU make` to the `DESCRIPTION` file. I don't think we can easily get around it in our `Makevars`
- The GHA on macOS currently fails with an error that is not clear to me what it means exactly (I am not sure if we should worry about that or not)

**Comment by csoneson** [comment]
Thanks - I'll add the system requirement. Not sure about the mac issue; the push run passed, the PR failed again. I don't really think it's an issue with the code.

**Comment by mbstadler** [comment]
I have one more point that is not clear to me and that I forgot to mention above:
`R CMD check` reports:
```
> checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... NOTE
    src/Makevars: SHLIB_OPENMP_CXXFLAGS is included in PKG_CXXFLAGS but not in PKG_LIBS
    src/Makevars: SHLIB_OPENMP_CFLAGS is included in PKG_LIBS but linking is by C++
    src/Makevars.win: SHLIB_OPENMP_CXXFLAGS is included in PKG_CXXFLAGS but not in PKG_LIBS
    src/Makevars.win: SHLIB_OPENMP_CFLAGS is included in PKG_LIBS but linking is by C++
  Use of these macros is discussed in sect 1.2.1.1 of ‘Writing R
  Extensions’. The macros for different languages may differ so the
  matching macro must be used in PKG_CXXFLAGS (etc) and match that used
  in PKG_LIBS (except for Fortran: see the manual).
```
Do you think that's something we should do?

**Comment by csoneson** [comment]
Oh - I see that I added the wrong flags to PKG_LIBS. I'll fix that too, thanks for noticing.

**Pull request merged**
